# Generated by Django 5.1.2 on 2024-10-30 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentorg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgmember',
            old_name='data_joined',
            new_name='date_joined',
        ),
    ]
